openapi: 3.0.3
info:
  title: ECOMM | Order API
  description: Ecomm is an e-commerce project created during the Level Up - PagoNxt by Alura. This API controls the orders section for the e-commerce. 
  version: 0.0.1
  termsOfService: https://mockapi.io
  contact:
    name: Leticia Monteiro
    email: contato@example.com
    url: https://mockapi.io
  license:
    name: "Lincença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
  description: Documentação burocrática
  url: https://mockapi.io
servers:
- url: https://6096015d116f3f00174b29ba.mockapi.io/
  description: API de Teste

paths:
  /api/orders:
    post: 
      tags:
      - orders
      summary: Place an Order
      description: Create a new order. 
      security: 
      - auth: [account]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Order'
        424: 
          description: Failed Dependency
          content: 
            application/json:
              example: Não foi possível realizar a compra!
        401: 
          description: Unauthorized 
          content:
            application/json:
              example: Você não tem autorização para realizar essa ação!

  /api/orders/{id}:
    parameters:
    - name: id 
      in: path 
      schema:
        type: string
        format: uuid
      required: true
    get: 
      tags:
      - orders
      summary: Fetch an Order
      description: Fetch an Order by ID 
      security: 
      - auth: [account]
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        404:
          description: Not Found
          content:
            application/json:
              example: Pedido não encontrado!


components: 
  schemas:
    Item: 
      type: object 
      properties: 
        name: 
          type: string
        quantity: 
          type: number
        fullPrice: 
          type: number
        discount:
          type: number
    Order:
      type: object
      properties:
        client:
          type: object
          properties: 
            id: 
              type: string
              format: uuid
            name:
              type: string
        deliveryAddress: 
          type: object
          properties: 
            street:
              type: string 
            number:
              type: string 
            complement: 
              type: string 
            zipCode:
              type: string 
            city:
              type: string 
            state:
              type: string 
        items:
          type: array
          items: 
            $ref: '#/components/schemas/Item'
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT