version: "3.9"
services:

  mongo:
    image: mongo
    volumes:
      - db-mongo-ecomm:/data/db
    container_name: mongo-ecomm
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret    
  
  mysql:
    image: mysql 
    volumes:
      - db-mysql-ecomm:/var/lib/mysql
    container_name: mysql-ecomm
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'ecomm_finance'
      MYSQL_ROOT_PASSWORD: secret
  
  redis:
    image: redis
    container_name: redis-ecomm
    volumes:
    - redis-data:/data
    restart: always
    ports:
    - 6379:6379

  product:
    build: ./product
    container_name: ecomm-product
    ports:
      - 3000:3000 
    volumes:
    - ./product:/app/product

  account: 
    build: ./account
    container_name: ecomm-account
    ports:
      - 3001:3001 
    volumes:
    - ./account:/app/account

  finance:
    build: ./finance
    container_name: ecomm_finance
    ports:
      - 3002:3002
    volumes:
    - ./finance:/app/finance

  order:
    build: ./order
    container_name: ecomm-order
    ports:
      - 3003:3003
    volumes: 
      - ./order:/app/order

volumes:
  db-mongo-ecomm:
  db-mysql-ecomm:
  redis-data:
  